### ISSUE TITLE
"no key" when using user_can?

### ISSUE THREAD

**Issue by ecdpalma** [kristianmandrup/cantango#14]
After some debug, what I've found is that it's trying to invalidate session[:permission], though the :permission key is not set session.

The trace:

```
cantango (0.9.4.5) lib/cantango/ability/cache/session_cache.rb:36:in `invalidate!'
cantango (0.9.4.5) lib/cantango/ability/cache.rb:67:in `invalidate!'
cantango (0.9.4.5) lib/cantango/ability/cache/writer.rb:16:in `save'
cantango (0.9.4.5) lib/cantango/ability/cache.rb:34:in `cache_rules!'
cantango (0.9.4.5) lib/cantango/ability/cache_helpers.rb:6:in `cache_rules!'
cantango (0.9.4.5) lib/cantango/ability/executor.rb:17:in `execute!'
cantango (0.9.4.5) lib/cantango/ability/engine_helpers.rb:6:in `block in execute_engines!'
cantango (0.9.4.5) lib/cantango/ability/engine_helpers.rb:13:in `block in each_engine'
cantango (0.9.4.5) lib/cantango/ability/engine_helpers.rb:12:in `each'
cantango (0.9.4.5) lib/cantango/ability/engine_helpers.rb:12:in `each_engine'
cantango (0.9.4.5) lib/cantango/ability/engine_helpers.rb:5:in `execute_engines!'
cantango (0.9.4.5) lib/cantango/cached_ability.rb:14:in `initialize'
cantango (0.9.4.5) lib/cantango/ability_executor.rb:25:in `new'
cantango (0.9.4.5) lib/cantango/ability_executor.rb:25:in `cached_ability'
cantango (0.9.4.5) lib/cantango/ability_executor.rb:17:in `cached_rules'
cantango (0.9.4.5) lib/cantango/ability_executor.rb:7:in `initialize'
cantango (0.9.4.5) lib/cantango/configuration/factory.rb:26:in `new'
cantango (0.9.4.5) lib/cantango/configuration/factory.rb:26:in `default_factory'
cantango (0.9.4.5) lib/cantango/configuration/factory.rb:17:in `factory_build'
cantango (0.9.4.5) lib/cantango/api/common.rb:7:in `create_ability'
cantango (0.9.4.5) lib/cantango/api/user/ability.rb:6:in `user_ability'
cantango (0.9.4.5) lib/cantango/api/user/ability.rb:10:in `current_user_ability'
(eval):3:in `user_can?'
app/views/layouts/application.html.erb:12:in `_app_views_layouts_application_html_erb__1953511322705147990_52161660__1246252357618705991'
actionpack (3.0.9) lib/action_view/template.rb:135:in `block in render'
activesupport (3.0.9) lib/active_support/notifications.rb:54:in `instrument'
actionpack (3.0.9) lib/action_view/template.rb:127:in `render'
actionpack (3.0.9) lib/action_view/render/layouts.rb:80:in `_render_layout'
actionpack (3.0.9) lib/action_view/render/rendering.rb:62:in `block in _render_template'
activesupport (3.0.9) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.9) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.9) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.9) lib/action_view/render/rendering.rb:56:in `_render_template'
actionpack (3.0.9) lib/action_view/render/rendering.rb:26:in `render'
actionpack (3.0.9) lib/abstract_controller/rendering.rb:115:in `_render_template'
actionpack (3.0.9) lib/abstract_controller/rendering.rb:109:in `render_to_body'
actionpack (3.0.9) lib/action_controller/metal/renderers.rb:47:in `render_to_body'
actionpack (3.0.9) lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
actionpack (3.0.9) lib/abstract_controller/rendering.rb:102:in `render_to_string'
actionpack (3.0.9) lib/abstract_controller/rendering.rb:93:in `render'
actionpack (3.0.9) lib/action_controller/metal/rendering.rb:17:in `render'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.0.9) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/ecdpalma/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/benchmark.rb:309:in `realtime'
activesupport (3.0.9) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
activerecord (3.0.9) lib/active_record/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.0.9) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.0.9) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (3.0.9) lib/abstract_controller/base.rb:150:in `process_action'
actionpack (3.0.9) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.9) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.0.9) lib/active_support/callbacks.rb:441:in `_run__3324046468054523801__process_action__2699832443661909176__callbacks'
activesupport (3.0.9) lib/active_support/callbacks.rb:410:in `_run_process_action_callbacks'
activesupport (3.0.9) lib/active_support/callbacks.rb:94:in `run_callbacks'
actionpack (3.0.9) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.0.9) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.9) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.9) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.9) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.0.9) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.0.9) lib/abstract_controller/base.rb:119:in `process'
actionpack (3.0.9) lib/abstract_controller/rendering.rb:41:in `process'
actionpack (3.0.9) lib/action_controller/metal.rb:138:in `dispatch'
actionpack (3.0.9) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.0.9) lib/action_controller/metal.rb:178:in `block in action'
actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:62:in `call'
actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:27:in `call'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in `block in recognize'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:68:in `optimized_each'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in `recognize'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.9) lib/action_dispatch/routing/route_set.rb:493:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.4) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/cookies.rb:302:in `call'
activerecord (3.0.9) lib/active_record/query_cache.rb:32:in `block in call'
activerecord (3.0.9) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.9) lib/active_record/query_cache.rb:12:in `cache'
activerecord (3.0.9) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
activesupport (3.0.9) lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
actionpack (3.0.9) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.4) lib/rack/sendfile.rb:106:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.0.9) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.4) lib/rack/runtime.rb:17:in `call'
activesupport (3.0.9) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.4) lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in `synchronize'
rack (1.2.4) lib/rack/lock.rb:11:in `call'
actionpack (3.0.9) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.9) lib/rails/application.rb:168:in `call'
railties (3.0.9) lib/rails/application.rb:77:in `method_missing'
railties (3.0.9) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.4) lib/rack/content_length.rb:13:in `call'
rack (1.2.4) lib/rack/handler/webrick.rb:52:in `service'
/home/ecdpalma/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/home/ecdpalma/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/home/ecdpalma/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by kristianmandrup** [comment]
Then I guess the fix is to patch the invalidate! logic so as to only invalidate the session if there is something to invalidate?

**Comment by ecdpalma** [comment]
Well, I don't know. It's your code :).

That seems to be "a" solution, but I ask myself whether session[:permission] makes any sense or not. In other words: Is the bug session[:permission] not being set, or else wrongly trying to invalidate it?

**Comment by kristianmandrup** [comment]
See the specs. There should be a spec testing the permission engine both with caching on and off. 
The session should only be used in caching mode, so one option would be to turn off this mode for the permission engine (see Engines on the wiki). I will try to fix this ASAP, I'm in the middle of extracting various parts of cantango (and some major refactoring) in order to make it easier to maintain etc.

**Comment by eendeego** [comment]
I'm also getting hit by this.

**Comment by adrianpike** [comment]
Also hitting this one. I do have a nil email on my Devise class, because I'm logging in with either a username or an email.

The suggested fix in the wiki (https://github.com/kristianmandrup/cantango/wiki/Troubleshooting) unfortunately doesn't work. :(

**Comment by kristianmandrup** [comment]
See the https://github.com/kristianmandrup/cantango/wiki/Configuration page:

CanTango.config.user do |user|
  user.unique_key_field = # some unique key (method/attribute) on the User class
end

Or simply turn off caching for starters. 

IMPORTANT: I've almost a completed a rewrite of cantango which in the new form is divided into various smaller gems (old project got way too big and unmaintainable!). Checkout _cantango-permits_ and go from there. The code has a better/cleaner design and has almost full spec coverage. 

I still need to finish the _cantango-permit_store_ gem and a few other extras, but the rest of the gems should pass all specs and work.

The new gems do not support caching yet either, so there is no session issue there. I will need to think/test more carefully when I get to that part. Good luck!

**Comment by reagleton** [comment]
In case this helps anyone else, I was also having this problem and this was my solution.

The setup,
- I'm using Devise with a username rather than an email
- I needed some rules to apply to all users
- Other rules will be dynamically applied to users based on their profile settings

I created a UserPermit (using the Cantango generator) so it would be applied against my User class

```
class UserPermit < CanTango::UserPermit
  def initialize ability
    super
  end

  protected

  def permit_rules
    # insert your can, cannot and any other rule statements here
    can :read, Interactive
    can :manage, User
    cannot :manage, Media
    # use any licenses here
  end

  module Cached
    def permit_rules
    end
  end

  module NonCached
    def permit_rules
    end
  end
end
```

My Cantango initializer was setup as follows where I had to turn caching off to get it to work. I don't know how to get it working with caching but I'm hoping my rules won't be too complex and need it,

```
CanTango.config do |config|
  config.debug!
  config.ability.mode = :no_cache
end

CanTango.config.user do |user|
  user.clear! # set user settings back to default
  user.unique_key_field = :username
end
```

I could then use checks like so (I had to use `user_can?` rather than `can?` because of the type of permit I was using),

```
<%= link_to('Media', media_index_path) if user_can? :read, Media %>
```
