### ISSUE TITLE
cantango with mongoid and devise

### ISSUE THREAD

**Issue by abhi-patel** [kristianmandrup/cantango#19]
I am trying to implement cantango with mongoid and devise.

I have successfully setup devise with mongoid. but i am trying to
configure cantango, every time it says

undefinded method 'user_can?' for <#class .....

after some debugging, it seems that cantango is not registering the
methods user_can? and user_cannot? with current user. instead it
attached this methods to CanTango::Rails::Helpers::ControllerHelper
and CanTango::Rails::Helpers::ViewHelper.

i already have added tango_user call in my user.rb, but no luck.

I also have tried to explicitly call the cantango core methods to add
this methods to the user model. but then it gives some weird error
that undefined method inject for string at cantango (0.9.4.7) lib/
cantango/permission_engine/statements.rb:19:in `parse_statements'

i tried changing every possible configuration options. but no luck.

I am using ruby 1.9.2 with rails 3.0.10.
Any help would be appreciated.

**Comment by sevenseacat** [comment]
Ran into the exact same issue - something to do with when CanTango loads its helpers compared to when Mongoid sets up the classes.

Remove the `tango_user` from your user.rb, and in your config/initializers/cantango.rb, add into the initialization block:

`config.users.register :user, User`

**Comment by kristianmandrup** [comment]
The #user_can? and similar cantango generated methods are supposed to be added to the ControllerHelper nd ViewHelper modules as you point out. Then in https://github.com/kristianmandrup/cantango/blob/master/lib/cantango/rails/engine.rb
these modules should be included into Rails Controllers and Views respectively.

``` ruby
    ActiveSupport.on_load(:action_controller) do
      include scope::Rails::Helpers::ControllerHelper
    end

    ActiveSupport.on_load(:action_view) do
      include scope::Rails::Helpers::ViewHelper
    end

class RailsEngine < ::Rails::Engine
    initializer "cantango.helpers" do
      CanTango.include_helpers(CanTango)
...
```

Yes, #tango_user should register the type of user and thus create the #user_can? method. Note that #user_can? should NOT be added to the User model.

I have almost completed a complete rewrite of cantango with much better test coverage, design and architecture. The new cantango is divided into multiple components (gems), such as _cantango-core_ etc.

**Comment by abhi-patel** [comment]
thank you @karpah for replying.

i tried that also, but after doing that somehow it stops recognizing the devise.
when i am trying to start the server after the change you have mentioned, it gives following error

app/models/user.rb:9:in `<class:User>': undefined method`devise' for User:Class (NoMethodError)
    from app/models/user.rb:1:in `<top (required)>'
    from /Users/admin/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:454:in`load'

**Comment by sevenseacat** [comment]
That I can't help with sorry, I don't use Devise.

@kristianmandrup Yes tango_user works with ActiveRecord, but not with Mongoid as I mentioned earlier.

**Comment by abhi-patel** [comment]
@kristianmandrup thanks for your reply.
and good to know that you are refining the design.

so for now is there any chance to get it working with mongoid and devise?

**Comment by kristianmandrup** [comment]
For Mongoid, check out:
https://github.com/kristianmandrup/cantango/blob/master/lib/cantango/configuration/models/mongoid.rb
https://github.com/kristianmandrup/cantango/blob/master/lib/cantango/rules/adaptor/mongoid.rb
https://github.com/kristianmandrup/cantango/blob/master/lib/cantango/rules/adaptor/generic.rb
https://github.com/kristianmandrup/cantango/blob/master/lib/cantango/rules/adaptor.rb

As you can see, this is unfortunately currently buggy and has not been tested. Look at the ActiveRecord adapter for hints.
Maybe better you look at `cantango-core` (has some specs)

https://github.com/kristianmandrup/cantango-core/blob/master/lib/cantango/adaptor/mongoid.rb
https://github.com/kristianmandrup/cantango-core/blob/master/lib/cantango/adaptor/mongo.rb
https://github.com/kristianmandrup/cantango-core/blob/master/lib/cantango/adaptor.rb

https://github.com/kristianmandrup/cantango-core/blob/master/spec/cantango/adaptor/active_record_spec.rb

I should hopefully soon finish the "new" cantango ;) 

Please see if you can fix this (write a spec) and if so, send me a pull request with the patch. Good luck!

**Comment by kristianmandrup** [comment]
If you are looking only to use permits, you might want to go with `cantango-permits` which uses the most recent (much better) design. There you can also investigate the specs and add your own functionality/patches. The code should also be much easier to follow. Good luck!

I still need to finish the `cantango-permission_store` project however... but this is a separate add-on.

**Comment by abhi-patel** [comment]
ok great. i will give a try to cantango-permits.

thanks.
